[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyhwm2014"
version = "1.1.1"
description = "Python interface for the prebuilt HWM14 neutral winds model"
readme = "README.rst"
requires-python = ">=3.10"
license = "MIT"
authors = [
    {name = "Ronald Ilma", email = "rilma@example.com"}
]
keywords = ["HWM14", "wind model", "atmospheric science"]
classifiers = [
    "Intended Audience :: Science/Research",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
]
dependencies = [
    "numpy>=1.23",
]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["pyhwm2014"]
namespaces = false

[tool.setuptools.package-data]
pyhwm2014 = [
    "py.typed",
    "*.pyd",
    "*.dll",
    "data/*.dat",
    "data/*.bin",
]
